name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  job:
    if: github.repository_owner == 'ShineyDev'

    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4

    - name: Configure
      id: configure
      uses: actions/configure-pages@v5

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade -r requirements.txt

    - name: Build
      run: python3 build.py ${{ steps.configure.outputs.base_url }}

    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy
      uses: actions/deploy-pages@v4
