name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

env:
  PYTHON_VERSION: 3.9

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build
      run: python3 build.py

    - name: Upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: build

  deploy:
    needs: build

    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
    - name: Deploy
      id: deploy
      uses: actions/deploy-pages@v2
